FROM l4t:latest

# Definition of a Device & Service
ENV POSITION=Runtime \
    SERVICE=build-container-image \
    AION_HOME=/var/lib/aion

RUN mkdir ${AION_HOME}
WORKDIR ${AION_HOME}
# Setup Directoties
RUN mkdir -p \
    $POSITION/$SERVICE
WORKDIR ${AION_HOME}/$POSITION/$SERVICE/
CMD ["/bin/sh", "-c", "while :; do sleep 10; done"]
